AUT-835 refactor: #time 783m Update ozmap-sdk version and nodes funct…
ozmap/node-red-contrib-ozmap pull request #10
Opened 2024-12-02 18:21 UTC by josalesmedeiros

Refatoração realizada para adequar a nova versão do OZmap SDK.

2024-12-02 20:21 UTC, raupp reviewed
Não fui até o final porque parece se repetir o mesmo problema em todos os arquivos. :) Depois de alterar eu refaço todo

2024-12-02 20:21 UTC, raupp commented on nodes/box/box.js
> +          401: 'disconnected',
401 deveria ser "Não autorizado"

2024-12-02 20:21 UTC, raupp commented on nodes/box/box.js
> +          503: 'internal server error',
503 geralmente é sobrecarga ou algo no servidor, erro pontual, não de codigo

2024-12-02 20:21 UTC, raupp commented on nodes/box/box.html
> +			createdAt1: { value: null },
createAt1 e updated1? Acho que vale nomes mais explicativos.

2024-12-02 20:21 UTC, raupp commented on nodes/box/box.js
> +        return [null, null];
O correto seria sempre enviar na saida 1 o erro, e na 2 o sucesso. Seguindo as boas praticas do callback(error,result)

2024-12-02 20:21 UTC, raupp commented on nodes/box/box.js
> +          options.page = options.page || 1;
page deveria ser 0? nunca lembro se é start=0 ou page =0 ;/

2024-12-02 20:21 UTC, raupp commented on nodes/cable/cable.js
> +        return [null, null];
Mesmo do anterior [error,result], pra seguir as boas praticas do callback

2024-12-02 20:21 UTC, raupp commented on nodes/cable/cable.js
> +          401: 'disconnected',
mesmo caso anterior dos tipos de erros

2024-12-02 20:21 UTC, raupp commented on nodes/client/client.js
> +        return [null, null];
mesmo caso anterior do [error,result] boas praticas de callback

2024-12-02 20:21 UTC, raupp commented on nodes/client/client.js
> +          401: 'disconnected',
mesmo caso dos erros anterior

2024-12-05 19:30 UTC, josalesmedeiros commented on nodes/box/box.html
> +			createdAt1: { value: null },
Esqueci de remover esses parâmetros a ideia é não tê-los nessa nova versão

2024-12-05 19:37 UTC, josalesmedeiros commented on nodes/box/box.js
> +          options.page = options.page || 1;
Pelo que testei, 0 ou 1 retornam a mesma page, mas a ideia era garantir que page tivesse um valor válido, porém sem sentido da forma que fiz, alterei para garantir que tem um número válido

2024-12-05 20:07 UTC, raupp requested changes

2024-12-05 20:07 UTC, raupp commented on nodes/box/box.html
> +      name: { value: 'Cable' },
isso aqui não deveria ser Box?

2024-12-05 20:07 UTC, raupp commented on nodes/network-connector/network-connector.js
> +            await ozmap.networkConnector
É estranha esta mistura de await e then/catch

2024-12-05 20:07 UTC, raupp commented on nodes/ozmap-connection/ozmap-connection.js
> +        console.warn('Ozmap foi iniciado');
era pra estar aqui, ou foi esquecido?

2024-12-05 20:07 UTC, raupp commented on nodes/ozmap-connection/ozmap-connection.js
> +        console.warn('Ozmap foi iniciado');
Aqui também ficou um console

2024-12-05 20:07 UTC, raupp commented on nodes/project/project.html
> +      name: { value: 'Cable' },
Cable aqui também? não deveria ser Project?

2024-12-05 20:07 UTC, raupp commented on nodes/property/property.js
> +        const options = {
Pra evitar estes multiplos ||, da pra criar um objeto default com tudo setado e depois usar um Object.assign(...

2024-12-05 20:07 UTC, raupp commented on nodes/property/property.js
> +              .then((data) => {
novamente estranho este await com then

2024-12-05 20:07 UTC, raupp commented on nodes/property/property.js
> +                  options.page += 1;
o que é esperado aqui? += 1 não vai pular 1?

2024-12-05 20:07 UTC, raupp commented on nodes/property/updateProperty.js
> +        .then((data) => {
novamente, mistura de await com then... acho estranho, não é um problema, só fica consfuso mesmo

2024-12-05 20:07 UTC, raupp commented on nodes/region/region.js
> +          limit: msg.payload?.limit || config.limit,
Mesma ideia de cima, criar um obejto default, com valores default... talvez até externo e usar para todos os casos

2024-12-05 20:07 UTC, raupp commented on nodes/region/region.js
> +              .then((data) => {
Mesmo caso. Await + then

2024-12-05 20:07 UTC, raupp commented on nodes/region/region.js
> +          msg.payload = await ozmap.region.findAll(options);
em alguns lugares tratamos os await com try/catch, outros não. Acho que vale um refactoringo no futuro pra ajustar todos. Task pro futuro

2024-12-05 20:07 UTC, raupp commented on nodes/user/updateUser.js
> +      await ozmap.users
await com then, é estranho

2024-12-05 20:07 UTC, raupp commented on nodes/user/user.js
> +          limit: msg.payload?.limit || config.limit,
mesma ideia dos casos anteriores, usar um objeto default pra todos, externo e só fazer um assign aqui

2024-12-05 20:07 UTC, raupp commented on nodes/user/user.js
> +                  options.page += 1;
mesmo caso aqui... += 1, não sei se vai ficar certo com o esperado

2024-12-06 12:12 UTC, josalesmedeiros commented on nodes/network-connector/network-connector.js
> +            await ozmap.networkConnector
Sem o "await" teremos o comando sendo chamando diversas vezes dentro do bloco sem aguardar a conclusão da promise para verificarmos se é  necessário chamar a próxima página

2024-12-06 12:25 UTC, josalesmedeiros commented on nodes/property/property.js
> +        const options = {
A ideia seria dessa forma?

`const options = {
          limit: config.limit,
          page: config.page,
          select: config.select,
          filter: config.filter,
          populate: config.populate,
          sorter: config.sorter,
};
Object.assign(options, msg.payload);`

2024-12-06 12:28 UTC, josalesmedeiros commented on nodes/property/property.js
> +                  options.page += 1;
Sim, a ideia é uma busca paginada indo até a última página que possui elementos

2024-12-12 15:19 UTC, josalesmedeiros commented on nodes/network-connector/network-connector.js
> +            await ozmap.networkConnector
Removemos o while para buscar apenas a página solicitada

2024-12-12 15:20 UTC, josalesmedeiros commented on nodes/ozmap-connection/ozmap-connection.js
> +        console.warn('Ozmap foi iniciado');
Na versão anterior tinha como uma forma de indicar que o OZmap autenticou com sucesso, porém, removi

2024-12-12 15:20 UTC, josalesmedeiros commented on nodes/property/property.js
> +                  options.page += 1;
Removemos o while para buscar apenas a página solicitada

2024-12-12 19:50 UTC, raupp approved these changes

2024-12-12 19:50 UTC, raupp commented on nodes/property/property.js
> +        const options = {
sim senhor. 
Pro futuro, podemos fazer este objeto que é comum a todos,  vir de um util/interface

2024-12-12 20:45 UTC, christianzirke reviewed
os comentários se aplicam a (virtualmente) todos os arquivos de model.js

2024-12-12 20:45 UTC, christianzirke commented on nodes/box/box.js
> +        if (options.page && !isNaN(options.page)) {
NaN é falsy, se options.page passou n precisa validar se é NaN

2024-12-12 20:45 UTC, christianzirke commented on nodes/client/client.js
> +      let ozmap = msg.ozmap || this.ozmapconnection?.ozmap;
```suggestion
      const ozmap = msg.ozmap || this.ozmapconnection?.ozmap;
```

2024-12-12 20:45 UTC, christianzirke commented on nodes/client/client.js
> +        Object.assign(options, msg.payload);
pq do assign como um passo separado? n aceita spread?
```suggestion
          sorter: config.sorter,
          ...msg.payload,
        };
```

2024-12-13 14:45 UTC, christianzirke approved these changes

2024-12-16 20:05 UTC, merged